### ISSUE TITLE
setState error on NotificationStack

### ISSUE THREAD

**Issue by sonhgc00016** [pburtchaell/react-notification#110] opened 2017-01-05 04:17 UTC
## Test Case
Add vast of notification at the same time

## Steps to Reproduce
Repeatedly click button addNotification

## Expected Behavior
Don't appear warning in inspect

## Actual Behavior
Appear **Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the StackedNotification component**

**Comment by pburtchaell** [comment] 2017-01-05 04:19
Does this error occur for the example?

**Comment by sonhgc00016** [comment] 2017-01-05 05:03
@pburtchaell yes, this error occur in example, too

**Comment by pburtchaell** [comment] 2017-01-05 05:37
> Repeatedly click button addNotification

So, to confirm, this error occurs in production? Can you provide more code? How are you using the component?

**Comment by sonhgc00016** [comment] 2017-01-05 07:28
This is my Notification component
```
import React, { Component } from 'react';
import { NotificationStack } from 'react-notification';
import { OrderedSet } from 'immutable';

class Notification extends Component {
  state = {
    notifications: OrderedSet(),
    // This is just used for the sake of an example to make sure
    // notifications have unique keys. In production, you should have
    // a different system for UIDs.
    count: 0,
  };

  addNotification = (message) => {
    const { notifications, count } = this.state;
    const newCount = count + 1;
    return this.setState({
      count: newCount,
      notifications: notifications.add({
        message: message,
        key: newCount,
        dismissAfter: 5000,
        onClick: () => this.removeNotification(newCount),
      })
    });
  }

  removeNotification = (count) => {
    const { notifications } = this.state;
    this.setState({
      notifications: notifications.filter(n => n.key !== count)
    });
  }

  render () {
    let { notifications } = this.state;
    return (
      <div>
        <NotificationStack
          notifications={notifications.toArray()}
          onDismiss={notification => this.setState({
            notifications: notifications.delete(notification)
          })}
        />
      </div>
    );
  }
}

export default Notification;
```
and use it in 
```
import React, { Component } from 'react';
import { Button } from 'semantic-ui-react';
import Notification from 'components/Notification';

class Register extends Component {

  onClick = () => {
    let { notification } = this.refs;
    notification.addNotification("This is sample notification");
  }
  render() {
    return (
      <div>
        <Notification ref='notification' />
        <Button primary onClick={this.onClick}>Show Notification</Button>
      </div>
    );
  }
}

export default Register;
```

Click button Show Notification and wait for several second and warning will be occur

**Comment by pburtchaell** [comment] 2017-01-20 01:05
It is difficult to parse your code. Can you reduce your code to only what code is needed to reproduce the error? I'm going to close this issue for now because I can't reproduce on my end.

**Closed by pburtchaell** 2017-01-20 01:05 UTC
Labels: bug

**Comment by JuhG** [comment] 2017-01-20 08:11
It's showing the same error for me too. Reproducing was easy, I cloned your repo and ran it, opened the Notification Tree example and clicked on the button for like 100 times. (It's already showing the warning for less notifications, but if you want to make sure.)

![notif](https://cloud.githubusercontent.com/assets/10765158/22140923/aca96b0a-deef-11e6-9d03-a699528a7e0d.png)

Thank you for taking the time, I like this plugin.

**Comment by shantp** [comment] 2017-04-21 22:29
Just installed this component today and I'm seeing this setState error when using NotificationStack. Why is the issue closed?

**Comment by pburtchaell** [comment] 2017-04-22 19:58
> when using NotificationStack 

Can you provide more information, e.g., example code?

**Comment by haolinj** [comment] 2017-04-26 07:11
Hi @shantp, I encountered the same issue, after a bit of digging in the code, I found that this is due to the `NotificationStack` will add 1 second to the `dismissAfter`: 
File notificationStack.js line 37: `if (!dismissNow) dismissAfter += index * 1000;` 

This incremented `dismissAfter` will be used to create `StackedNotification`. So in file stackedNotification.js line 38: `this.dismissTimeout = setTimeout(this.setState.bind(this, {
      isActive: false
    }), dismissAfter);` will have incremented `dismissAfter`.

But we will execute `onDismiss` to remove the notification component with original `dismissAfter`, the component will be removed before the later `this.setState.bind...` is called.

For example: if the I create a `NotificationStack` with `dismissAfter` 5 seconds, the created notification component will be unmounted after 5 seconds, but the `this.setState.bind(...` may run after 6 seconds due to the `dismissAfter += index * 1000`. So it causes setState on unmounted component error.

A work around is to add `dismissInOrder={false}` on `NotificationStack`, so it will not add 1 second to the `dismissAfter` value.

Please let me know if I made any mistake on the findings.

**Comment by brianespinosa** [comment] 2017-07-06 20:25
@haolinj thanks for digging into that. Your workaround looks like solves our issue for now. 

@pburtchaell based on the above, I think this issue should be reopened so someone can take a look and submit a PR with a solution to handle this case without a workaround. Thoughts?
